from src.patents.base_client import BasePatentClient, PatentClientError
from src.patents.epo_auth import (
    EPOAuthClient,
    EPOAuthError,
    EPOHTTPError,
    EPOMissingCredentialsError,
    EPONetworkError,
    EPOResponseError,
)
from src.patents.epo_client import (
    EPOClient,
    EPOClientAuthenticationError,
    EPOClientError,
    EPOClientHTTPError,
    EPOClientNetworkError,
    EPOClientResponseError,
)
from src.patents.discovery_service import (
    DiscoveryStats,
    EPODiscoveryError,
    EPODiscoveryService,
)
from src.patents.epo_parser import EPOParserError, parse_epo_search_response
from src.patents.inpass_client import (
    InPassBrowserError,
    InPassCaptchaTimeoutError,
    InPassClient,
    InPassClientError,
    InPassNavigationError,
    InPassSearchConfig,
    InPassSearchError,
    InPassSearchResultRow,
)
from src.patents.inpass_ingestion_service import (
    InPassIngestionError,
    InPassIngestionPersistenceError,
    InPassIngestionResult,
    InPassIngestionSearchError,
    InPassIngestionService,
)
from src.patents.discovery_strategy import (
    BasePatentQueryGenerator,
    DeterministicPatentQueryGenerator,
    InPassDiscoveryResult,
    InPassDiscoveryStrategy,
)
from src.patents.research_config import (
    COSMETICS_RESEARCH_CONFIG,
    DEFAULT_RESEARCH_CONFIG,
    WATER_RESEARCH_CONFIG,
    PatentResearchConfig,
    ResearchDomainConfig,
    get_default_research_config,
)
from src.patents.inpass_parser import (
    InPassParserError,
    parse_inpass_details,
    parse_inpass_patent_details,
)
from src.patents.models import (
    IndianPatentRecord,
    InPassPatentRecord,
    PatentRecord,
    PersonOrOrganization,
    build_canonical_url,
    is_valid_patent_number,
    normalize_patent_components,
    normalize_patent_number,
    validate_patent_number,
)

__all__ = [
    "BasePatentClient",
    "BasePatentQueryGenerator",
    "COSMETICS_RESEARCH_CONFIG",
    "DEFAULT_RESEARCH_CONFIG",
    "DeterministicPatentQueryGenerator",
    "DiscoveryStats",
    "EPOAuthClient",
    "EPOAuthError",
    "EPOClient",
    "EPOClientAuthenticationError",
    "EPOClientError",
    "EPOClientHTTPError",
    "EPOClientNetworkError",
    "EPOClientResponseError",
    "EPODiscoveryError",
    "EPODiscoveryService",
    "EPOHTTPError",
    "EPOIngestionDiscoveryError",
    "EPOIngestionError",
    "EPOIngestionRepositoryError",
    "EPOIngestionService",
    "EPOMissingCredentialsError",
    "EPONetworkError",
    "EPOParserError",
    "EPOResponseError",
    "IndianPatentRecord",
    "IngestionResult",
    "InPassBrowserError",
    "InPassCaptchaTimeoutError",
    "InPassClient",
    "InPassClientError",
    "InPassDiscoveryResult",
    "InPassDiscoveryStrategy",
    "InPassIngestionError",
    "InPassIngestionPersistenceError",
    "InPassIngestionResult",
    "InPassIngestionSearchError",
    "InPassIngestionService",
    "InPassNavigationError",
    "InPassParserError",
    "InPassPatentRecord",
    "InPassSearchConfig",
    "InPassSearchError",
    "InPassSearchResultRow",
    "PatentClientError",
    "PatentRecord",
    "PatentRepository",
    "PersonOrOrganization",
    "ResearchRunPatentReader",
    "USPTOClient",
    "USPTOClientError",
    "USPTOHTTPError",
    "USPTOMissingAPIKeyError",
    "USPTONetworkError",
    "USPTOResponseError",
    "build_canonical_url",
    "is_valid_patent_number",
    "normalize_patent_components",
    "normalize_patent_number",
    "parse_epo_search_response",
    "parse_inpass_details",
    "parse_inpass_patent_details",
    "PatentResearchConfig",
    "ResearchDomainConfig",
    "validate_patent_number",
    "WATER_RESEARCH_CONFIG",
    "get_default_research_config",
]


